### ISSUE TITLE
have to use advanced programming technics to implement guide

### ISSUE THREAD

**Issue by illeagleemmygrands** [adolfintel/Windows10-Privacy#10]
WHY U NO UPLOAD BATCH SCRIPT?? HAVE TO TYPE ALL OF THIS BY HAND
![http://i0.kym-cdn.com/entries/icons/original/000/004/006/YUNO.jpg](http://i0.kym-cdn.com/entries/icons/original/000/004/006/YUNO.jpg)

**Comment by adolfintel** [comment]
Because there are several reboots involved and it would be a pain in the ass to make.
Also that meme is stale.

**Comment by andregeronimocs** [comment]
Just a note on this request.

I'm no programmer, but I've been working on some .bat and .ps1 files to acquire the same results and can confirm F. Dossena's observations about the necessary reboots and the complexity of getting t it all coded. I got it simplified into 5 files until now and may share it after some more tinkering, but just for reference, as I think this guide can be improved with some other codes, there's Disassembler0's Win10-Initial-Setup-Script that automates a great part of the code if anyone is interested: https://github.com/Disassembler0/Win10-Initial-Setup-Script

**Comment by adolfintel** [comment]
I tried making a script years ago but gave up. Those files could be useful if I tried again though
