### ISSUE TITLE
Ethernet broke

### ISSUE THREAD

**Issue by BigButcherBoy** [adolfintel/Windows10-Privacy#11]
Followed it from start to finish, but my ethernet wouldn't work after. No yellow warning but tried to reinstall the driver and it came up after that. Now it constantly says 'identifying...'. I set a restore point first but not sure what the cause is for this, thought id let you know.

**Comment by adolfintel** [comment]
Broken DHCP, uninstall Tinywall and reinstall it, make sure you allow DHCP to go through

**Comment by adolfintel** [comment]
It happened on my laptop too when I updated to 1709

**Comment by legendarynacar** [comment]
It happened to me either. I just changed to mode to learning and everything become fine. I think we need to look up docs of tinywall to understand it better.

**Comment by adolfintel** [comment]
I don't know what triggers it exactly, but it's tinywall. I sincerely hope they fix it because it's not even open source :(

On 2 May 2018 22:32:42 CEST, Legendary Nacar <notifications@github.com> wrote:
>It happened to me either. I just changed to mode to learning and
>everything become fine. I think we need to look up docs of tinywall to
>understand it better.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/Windows10-Privacy/issues/11#issuecomment-386111451

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BigButcherBoy** [comment]
Both tinywall and simplewall just cause my internet to not work when enabled, even if I allow DHCP on simplewall.

**Comment by adolfintel** [comment]
Autolearn lets everything through and adds applications automatically. It's not safe to keep it that way forever. If you set it back to normal and it breaks your ethernet again, then there is some bug in the firewall.
You could try changing your network driver, it might fix the problem.

On 3 May 2018 20:19:30 CEST, BigButcherBoy <notifications@github.com> wrote:
>Okay, I enabled the autolearn function in tinywall and it works fine
>now.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/Windows10-Privacy/issues/11#issuecomment-386389694

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
