### ISSUE TITLE
Microphone stopped working

### ISSUE THREAD

**Issue by Bojanits** [adolfintel/Windows10-Privacy#12]
After i completed all of these my microphone input stopped working, tried many things online and it still doesn't register voice input.

**Comment by adolfintel** [comment]
I use it regularly, are you sure it's not your sound driver?

**Comment by Bojanits** [comment]
Yes, I just checked my drivers and everything is up to date.

**Comment by adolfintel** [comment]
What sound card do you have?

**Comment by Bojanits** [comment]
Realtek High Definition Audio, its the built in one for my laptop (asus gl551jm-dh71)

**Comment by Bojanits** [comment]
When I go to Control Panel > Ease of Access > setup Microphone, I get the error "The wizard could not start"
![error](https://user-images.githubusercontent.com/23128816/40015522-a6a2aec2-5781-11e8-9924-02fc60de82a6.PNG)

**Comment by adolfintel** [comment]
Oh, you meant the speech recognition, not the microphone itself.
I tested it on my comptuer and it starts, could it be that classic shell is interfering?
![image](https://user-images.githubusercontent.com/16307689/40015950-232bcd24-57b5-11e8-94e3-916b1e4c690b.png)

**Comment by Bojanits** [comment]
No, the microphone still doesn't pick up sound (no green bars next to microphone on recording devices). I also uninstalled classic shell and restarted my computer and it still doesn't work. Maybe my hardware failed at an coincidental time.

**Comment by adolfintel** [comment]
So if you go here you don't see the microphone? Or does it just pick up no sound?
![image](https://user-images.githubusercontent.com/16307689/40016806-ddfcc34a-57b7-11e8-9277-56f1cbf160d7.png)

**Comment by Bojanits** [comment]
I see the microphone, it just doesnt pick up any sound. Its not muted either.

**Comment by adolfintel** [comment]
Does it pick up something if you plug in an external microphone into the jack?

**Comment by Bojanits** [comment]
I plugged in apple headphones which contain a mic and sound is able to play through them but the microphone doesnt work still.

**Comment by adolfintel** [comment]
I'm sure it's not related to the guide, but let's rule out the driver issue. Go to the asus website and download the sound driver that they provide for your laptop. I know, it's not the latest version, but maybe it has some config file that your sound card needs

**Comment by Bojanits** [comment]
unfortunately they don't offer a sound driver :/

**Comment by adolfintel** [comment]
Hmmm, wanna try installing this one?
http://www.guru3d.com/files-details/realtek-hd-audio-2-79-driver-download.html

**Comment by Bojanits** [comment]
No luck, I think its a problem on my end most likely.

**Comment by SDMU** [comment]
Hello ! I'm facing the same issue , my microphone does not pick up anything though all drivers seem to be just fine ! Did you manage to resolve your issue ?

**Comment by Bojanits** [comment]
Turns out all the steps to remove the bloatware just mess ur audio up. I just ended up reverting everything back and keeping the bloatware since I need to use my mic a lot

**Comment by SDMU** [comment]
The 1st time I faced this issue (which was also the 1st time I followed this guide), I created another user account on the same pc . The microphone started working on the new user account . The microphone stopped working when I switched back to my original user account.

This time before following the guide , I had " completely reset my pc" . I had hoped that because of this , there won't be any issues following the guide . However I still faced this issue .

There must be a particular program/file getting deleted which causes the microphone to stop working .

**Comment by adolfintel** [comment]
It's hard for me to track down what's the cause of this, because the microphone works on all my machines. Maybe it's something that you guys have in common?

On July 11, 2018 6:32:03 PM GMT+02:00, SDMU <notifications@github.com> wrote:
>The 1st time I faced this issue (which was also the 1st time I followed
>this guide), I created another user account on the same pc . The
>microphone started working on the new user account . The microphone
>stopped working when I switched back to my original user account.
>
>This time before following the guide , I had " completely reset my pc"
>. I had hoped that because of this , there won't be any issues
>following the guide . However I still faced this issue .
>
>There must be a particular program/file getting deleted which causes
>the microphone to stop working . 
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/Windows10-Privacy/issues/12#issuecomment-404232643

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SDMU** [comment]
Is it possible for me to supply any kind of data that might help you in some way .

The only other option is to apply every fix in the guide one-by-one and check at every step whether the microphone is working or not .

**Comment by adolfintel** [comment]
If you could do the step by step thing it would be perfect, that's usually how I find problems with the guide

On July 11, 2018 6:56:14 PM GMT+02:00, SDMU <notifications@github.com> wrote:
>Is it possible for me to supply any kind of data that might help you in
>some way .
>
>The only other option is to apply every fix in the guide one-by-one and
>check at every step whether the microphone is working or not .
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/Windows10-Privacy/issues/12#issuecomment-404239770

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SDMU** [comment]
Ok , I'll do that and update this thread !

**Comment by SDMU** [comment]
Hello ! My microphone started working again.

1.Go to settings 
2.Privacy
3.Microphone privacy settings
4.Make sure these 2 settings are enabled
4a. Microphone access for this device is on.
4b. Allow apps to access your microphone is on.
5. For good measure I allowed Cortana and Win32WebViewHost to access my microphone (since they were the only apps listed)
6. For even more good measure ,I went to Camera Privacy settings and made sure the following 2 settings are enabled
6a. Camera access for this device is on.
6b. Allow apps to access your camera is on.

**Comment by SDMU** [comment]
I am not sure whether :
A. Allowing cortana and win32wblebviewhost access to microphone is needed.
B.allowing apps to access camera is needed.
I am a bit scared to disable them now !

**Comment by adolfintel** [comment]
Hmm maybe the second one, I'll have to test it

On July 11, 2018 9:16:16 PM GMT+02:00, SDMU <notifications@github.com> wrote:
>I am not sure whether :
>A. Allowing cortana and win32wblebviewhost access to microphone is
>needed.
>B.allowing apps to access camera is needed.
>I am a bit scared to disable them now !
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/Windows10-Privacy/issues/12#issuecomment-404280472

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adolfintel** [comment]
In Settings > Privacy > Microphone there's this setting.
![image](https://user-images.githubusercontent.com/16307689/42615109-f2694f50-85a8-11e8-98be-fece82e4f02f.png)
If I turn it off, the microphone doesn't work. I didn't disable it in my guide though.
![image](https://user-images.githubusercontent.com/16307689/42615123-07d5544c-85a9-11e8-97fe-5b8b0372d55c.png)
This other setting only applies to UWP apps apparently

**Comment by adolfintel** [comment]
Same thing for the camera

**Comment by adolfintel** [comment]
The problem appeared on one of my machines after the 17134.165 update.
I don't think it's related to any of the changes in the guide but I was unable to fix it.
I can monitor the sound from the microphone but any application trying to use it will fail, through all APIs. The indicator also doesn't move.
Windows says that the Windows Audio or the Windows Audio Endpoint Builder services are not running, but they are.

**Comment by SDMU** [comment]
I guess Windows wants the computers' camera to access the microphone at all costs (sneakysneaky) !

**Comment by adolfintel** [comment]
They fixed it! I just installed the 17134.228 cumulative update and the sound is working again
