### ISSUE TITLE
Windows Spotlight

### ISSUE THREAD

**Issue by abhijithvijayan** [adolfintel/Windows10-Privacy#17]
Issues with windows spotlight. Stuck with a stupid lockscreen wallpaper.

**Comment by adolfintel** [comment]
Didn't you disable it?

**Comment by abhijithvijayan** [comment]
I disabled it but at times when windows restarts the wallpaper somehow changes back to the stupid ones. So I enabled Windows Spotlight and it is not changing. It's that my custom lockscreen wallpaper changes most of the time automatically to the default one

**Comment by SDMU** [comment]
There should be 3 options : Windows Spotlight / Picture / Slideshow . 
Are you not able to select Picture ?

**Comment by abhijithvijayan** [comment]
Yeah I can select the picture and apply one. It works for sometime and at some boot it reverts back to the old image but the option stays intact

**Comment by abhijithvijayan** [comment]
Anything?

**Comment by adolfintel** [comment]
I've seen this thing after cumulative updates but then it fixes itself. It's not related to the guide

**Comment by abhijithvijayan** [comment]
https://mergy.org/2016/05/fixing-the-windows-10-pre-login-background-screen/

This article helped. I deleted the directory that included the default wallpaper that windows created some time ago.
