### ISSUE TITLE
VC Redist 2015 won't install

### ISSUE THREAD

**Issue by BigButcherBoy** [adolfintel/Windows10-Privacy#18]
Since doing this my computer just says install failed, only noticed this when trying to install a program that relies on it and it in itself couldn't download the files from Microsoft, tried to install it separately and it still didn't want to do anything.

Could be unrelated but was wondering if this was happening for anyone else, I have no issue installing any of the others just 2015 which is bizarre.

**Comment by adolfintel** [comment]
You have to allow the installer through the firewall (or disable the firewall) if it's an online installer.
Here's the offline installer if you need it: https://www.microsoft.com/en-us/download/details.aspx?id=48145

Other than that, VC redist 2015 is installed on my computer so it's not related to the guide

**Comment by BigButcherBoy** [comment]
Yeah just did some digging and turns out I had 2017 installed which held registry keys used in 2015 also, so the installer was thinking it was already installed, thanks and sorry for the false issue!
