### ISSUE TITLE
Pre installed game shortcuts stuck in start menu

### ISSUE THREAD

**Issue by thaeox** [adolfintel/Windows10-Privacy#19]
I cannot figure out how to remove a couple of the preinstalled game shortcuts from the start menu, namely Candy Crush. I feel like I’ve tried everything

**Comment by adolfintel** [comment]
You uninstall them and they come back?
In this case, all you have to do is wait. Open the store, go to downloads and let it check for updates and download everything until it says there are no more updates, then remove them and proceed with the guide.

**Comment by thaeox** [comment]
I did that and they still did not go away. I did solve the problem though with a System Reset.

**Comment by adolfintel** [comment]
I guess they really wanted you to play candy crush.
So sad...
