### ISSUE TITLE
Is there a way to remove the lock screen permanently?

### ISSUE THREAD

**Issue by seiterseiter** [adolfintel/Windows10-Privacy#2]
I mean so it doesnt even show up on start up. Without the task scheduler trick.

**Comment by adolfintel** [comment]
Try this .reg file
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization]
"NoLockScreen"=dword:00000001
```

**Comment by seiterseiter** [comment]
That doesnt work anymore after the Windows 10 Anniversary update. It just gets reset to 0 after each boot.

**Comment by adolfintel** [comment]
Oh ok, I used that registry file with 8.1.
I don't know of any other way to disable the lock screen, but I'm not sure I understand what you are looking for. Unless you have a password or a microsoft account you don't even see the lock screen

**Comment by seiterseiter** [comment]
Yeah I do have a password but its really annoying having to click multiple times to get the lockscreen to go away and then enter my password.

**Comment by adolfintel** [comment]
Mine goes straight to the password screen... I'll check and get back to you soon

**Comment by seiterseiter** [comment]
Im on the Creators update if that makes a difference.

**Comment by adolfintel** [comment]
Me too

**Comment by adolfintel** [comment]
I have this set to 1, it does not reset to 0 as you said.

![2017-09-10 09_57_06-registry editor](https://user-images.githubusercontent.com/16307689/30247200-b9fab65c-960e-11e7-9ec4-953db0c8b912.png)

**Comment by seiterseiter** [comment]
Weird... It doesnt exactly reset to 0, it just doesnt effect anything.

**Comment by adolfintel** [comment]
If I set it to 0 I get the lock screen, if I set it to 1 it goes to the password screen.

**Comment by seiterseiter** [comment]
Even after you reboot your pc?

**Comment by adolfintel** [comment]
Yes, I had this turned on for so long that I even forgot about it

**Comment by seiterseiter** [comment]
Im meaning the lockscreen that looks like [http://winaero.com/blog/wp-content/uploads/2016/09/Windows-10-lockscreen-no-network-icon.png](url) , is that what you are meaning?

**Comment by adolfintel** [comment]
Your link doesn't open.
I mean the lock screen with the picture, the time and some icons

**Comment by seiterseiter** [comment]
It should work not but thats what im meaning too.

**Comment by adolfintel** [comment]
Maybe you have some other program interfering with the setting. Do you use some software to customize the looks of windows?

**Comment by seiterseiter** [comment]
I did have yamisoft windows 10 manager but it was uninstalled. Other then that I have no customization programs.

**Comment by adolfintel** [comment]
Never heard of it.
You should check your startup applications, the services and the scheduled tasks to see if there's anything unusual. It may take some time though

**Comment by seiterseiter** [comment]
Okay thanks, ill go have a look now and get back to you.

**Comment by adolfintel** [comment]
Sure :)

**Comment by SDMU** [comment]
can we add the above regedit to the below path ?

Computer\HKEY_USERS\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize

**Comment by SDMU** [comment]
The above path contains only the file named default.
It does not contain the files : NoLockScreen and NoLockScreenCamera . If this is the correct path those files need to be created , but I don't know how to properly create those files..
