### ISSUE TITLE
Not able to remove or install any Windows Store apps

### ISSUE THREAD

**Issue by KKynno** [adolfintel/Windows10-Privacy#20]
Hello,

I followed most of steps and there is a step where the Windows Store stop working. (Get button disappear and I can't deinstall any apps.) 

Is there a way to enable again only these features ? 

Thank you 🙂

**Comment by adolfintel** [comment]
Hi,

No, the install services were removed, and you should remove the store too. If you need to install some UWP app (like some cracked store game), you can still do that manually.

**Comment by KKynno** [comment]
Would you please tell me what step remove the install services so I can avoid these ?

**Comment by adolfintel** [comment]
It *should* be this command in the telemetry and unnecessary services section:
```sc delete InstallService```

I can't guarantee that it will work though, I imagine the guide breaks other things involved in the store.

**Comment by KKynno** [comment]
Yep, it seems to be that line. I removed it and it seems to work fine, the button is still there. 

Thank you man. :)
