### ISSUE TITLE
please replace service deletion with service disabling

### ISSUE THREAD

**Issue by mailinglists35** [adolfintel/Windows10-Privacy#21]
instead of "sc delete blah" please do ["sc config blah start= disable"
](https://superuser.com/a/460077)
this is less destructive and can be re-enabled when needed

**Comment by adolfintel** [comment]
That would be nice, but Windows re-enables those services if you don't delete them.

**Comment by mailinglists35** [comment]
>Windows re-enables those services

not if you [set security permissions](https://blogs.msmvps.com/erikr/2007/09/26/set-permissions-on-a-specific-service-windows/) for them

**Comment by mailinglists35** [comment]
and you can later [reset to original permissions](https://serverfault.com/questions/645776/how-to-reset-service-permissions-after-messing-up-with-sc-sdset)

**Comment by adolfintel** [comment]
Oh, I wasn't aware of that, I'll take a look at it then
