### ISSUE TITLE
Add ImgBot to reduce the file size of pics

### ISSUE THREAD

**Issue by Eddi2015** [adolfintel/Windows10-Privacy#26]
Please add ImgBot to this repo, so that the page loads faster. https://github.com/apps/imgbot

It doesn't hurt and saves bandwith.

**Comment by adolfintel** [comment]
I never heard of it, I'll check it out.

**Comment by Eddi2015** [comment]
Thank you. Of course you can apply image-optimization in general to all of your projects/websites (also helps for SEO).
