### ISSUE TITLE
Removing reference to wscsvc causes issues if you still have Windows Defender

### ISSUE THREAD

**Issue by jlagden** [adolfintel/Windows10-Privacy#27]
I like to keep Windows Defender on my system, but tweak the individual settings as required.
However if I follow all in **Removing Telemetry and other unnecessary services** this particular line seems to stop me accessing Windows Defender.

%I in ('reg query "HKLM\SYSTEM\CurrentControlSet\Services" /k /f "wscsvc" ^| find /i "wscsvc"') do (reg delete %I /f)

Should this really be grouped with the window defender stuff? Or is there some reporting or similar this service does?

**Comment by adolfintel** [comment]
It's the Windows Security Center service so that will certainly break the UI for defender, and possibly more.
I strongly suggest that you do not keep defender on your computer, it is an absolute privacy nightmare.
