### ISSUE TITLE
Firewall suggestion [Enhancement]

### ISSUE THREAD

**Issue by duttyend** [adolfintel/Windows10-Privacy#3]
Thank you so much for this excellent and very exhaustive guide !

I would like to point out a free and open source alternative for the "_Optional: use a firewall!_" section called **_simplewall_** : https://github.com/henrypp/simplewall/releases
I have been using it for a couple of months and it is very powerful yet very light and updated very often !

Have a great day !

**Comment by adolfintel** [comment]
Seems very similar to Tinywall, I'll check it out. Thank you :)

**Comment by daslicht** [comment]
how about : https://www.binisoft.org/wfc.php ?
