### ISSUE TITLE
Has lusrmgr.msc been tested?

### ISSUE THREAD

**Issue by Jake1702** [adolfintel/Windows10-Privacy#32]
I noticed the page says not to follow it if you need to add more user accounts as it's a bit broken. I'm assuming this means the settings app feature to add user accounts. Would I be correct in assuming the functionality of lusrmgr.msc (Local Users and Groups Management Console) still functions as it should? Perhaps note of this should be added to the guide if that's the case.

**Comment by adolfintel** [comment]
Unfortunately no, it doesn't work either way.
I'm not sure why, it worked fine before 1809, now I'm just greeted with a black screen and no dwm.
