### ISSUE TITLE
Can't remove candy crush and other bloatware

### ISSUE THREAD

**Issue by taich001** [adolfintel/Windows10-Privacy#33]
I can not remove candy crush, news, netflix and other stuff after new installation of win 10 prof.
You can right click remove but nothing happens, on other ocations the item in menu disapears but another previously removed app reapears instead.

If you play a while with removing items from menu you might succed, but after a while all the previously removed f.... stuff reapears again.

Great feature !?@$

**Comment by adolfintel** [comment]
It happens sometimes, all you have to do is wait, reboot, make absolutely sure that the store is finished downloading when you uninstall them.
