### ISSUE TITLE
Reverse changes to be able to use Store

### ISSUE THREAD

**Issue by Skoddd** [adolfintel/Windows10-Privacy#34]
I know it says "You need to download anything from the Windows Store (including distros for the Linux subsystem if you want to use it" but is there really no way to reverse some of the procedures to be able to use windows store?

**Comment by adolfintel** [comment]
Nope, you have to reinstall windows to fully revert.
A lot of changes (but not all) can be reverted with this command though: ``dism /Online /Cleanup-Image /RestoreHealth``

**Comment by Skoddd** [comment]
I'm not looking to fully revert, just need to be able to install something from the store. Is there a way to only revert the changes pertaining to this?

**Comment by adolfintel** [comment]
Not that I know of, sorry

**Comment by Skoddd** [comment]
[This ](https://neosmart.net/wiki/windows-10-repair-installation/)did the trick

**Comment by lazerl0rd** [comment]
@Skoddd if you like I made one based on this that let's you use Store and practically all Windows features, look here at lasterhub.me (download ScriptWINg and use the batch file inside the anti_privacy folder). The source for my stuff is at https://gitlab.com/lazerl0rd/scriptwing.
