### ISSUE TITLE
Attach  importance for governmental users 

### ISSUE THREAD

**Issue by F3000** [adolfintel/Windows10-Privacy#35]
hi , it would be nice if you can add a section with guides how to implement windows 10 /office 2016 on pc’s in the government

**Comment by adolfintel** [comment]
I don't use MS Office so I don't know what needs to be done for privacy.
Use Libreoffice if you can.

**Comment by F3000** [comment]
Do you have some recommendations which ip addresses I can block on my firewall ?  I think with the built in firewall I can't block all important things.
