### ISSUE TITLE
Disable Security and Maintenance in Notification Center Messages

### ISSUE THREAD

**Issue by rizomabr** [adolfintel/Windows10-Privacy#36]
After removing Windows Defender, you can right click the reminder notification or use this code to hide it:

`reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.SecurityAndMaintenance" /v "Enabled" /t REG_DWORD /d 0 /f`

**Comment by adolfintel** [comment]
Thanks, I'll add this
