### ISSUE TITLE
Powershell commands to remove Windows Optional Features

### ISSUE THREAD

**Issue by rizomabr** [adolfintel/Windows10-Privacy#37]
To remove  Windows Media Player:
`Get-WindowsPackage -Online | Where PackageName -like *MediaPlayer* | Remove-WindowsPackage -Online -NoRestart`

To remove Internet Explorer:
`Get-WindowsPackage -Online | Where PackageName -like *InternetExplorer* | Remove-WindowsPackage -Online -NoRestart`

To remove Quick Assist:
`Get-WindowsPackage -Online | Where PackageName -like *QuickAssist* | Remove-WindowsPackage -Online -NoRestart`

To remove Hello Face:
`Get-WindowsPackage -Online | Where PackageName -like *Hello-Face* | Remove-WindowsPackage -Online -NoRestart`

**Comment by adolfintel** [comment]
Thanks, I'll update the guide with these commands

**Comment by rizomabr** [comment]
This one is on PowerShell, not on Command Prompt:
`Get-WindowsPackage -Online | Where PackageName -like *InternetExplorer* | Remove-WindowsPackage -Online -NoRestart`

If you wanna run the whole script from the Prompt, just add
"powershell.exe -Command" before the command. Example:
`powershell.exe -Command "Get-WindowsPackage -Online | Where PackageName -like *InternetExplorer* | Remove-WindowsPackage -Online -NoRestart"`

**Comment by adolfintel** [comment]
Yea, that wasn't intentional, I'll fix it
