### ISSUE TITLE
Far cleaner way to disable Compatibility telemetry

### ISSUE THREAD

**Issue by pal1000** [adolfintel/Windows10-Privacy#4]
Instead of messing with CompatTelRunner.exe file you can disable it in a more cleaner way using Image File Execution Options Debugger Value:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\CompatTelRunner.exe]
"Debugger"="%windir%\\system32\\taskkill.exe"


```
Setting this value to an executable designed to kill processes disables it. Being far cleaner, Windows won't re-enable it with almost each update.

**Comment by adolfintel** [comment]
Hahahah that is so fucking brutal, I love it.
I'll test it out and add it to the guide if it works well

**Comment by adolfintel** [comment]
Looks like it works :)
I'll use this command to do it automatically:
```
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Option\CompatTelRunner.exe" /v Debugger /t REG_SZ /d "%windir%\System32\taskkill.exe" /f
```

**Comment by NorbertWebb** [comment]
Easy fix 2019 [CompatTelRunner.exe](https://geeksadvice.com/fix-microsoft-compatibility-telemetry-high-cpu-usage/) for everyone! 

> Launch Run window by pressing down Windows key and R letter on your keyboard at the same time.
Type taskschd.msc and press Enter or OK.
Now, expand the folders in the given order – Task Scheduler Library > Microsoft > Windows > Application Experience. Find a task called Microsoft Compatibility Appraiser and right-click on it. Select Disable.

**Comment by pal1000** [comment]
@NorbertWebb, there is a higher risk Microsoft resets that task with a cumulative update than how it's done in this open source guide.

**Comment by adolfintel** [comment]
I agree with @pal1000, windows updates sometimes change policy settings
