### ISSUE TITLE
no RDP after 

### ISSUE THREAD

**Issue by Julien-nl** [adolfintel/Windows10-Privacy#44]
Hi guys,
i have followed the steps, unfortunately i cannot connect to Windows 10 1809 RDP.
Remote desktop is enabled and firewall is off but no connection.
i can ping the machine i can connect to it share c$ but not remote desktop.
can you please advies how to get to the button of this ?

big thank you

**Comment by adolfintel** [comment]
That is intentional, some services required to use RDP have been removed

**Comment by Julien-nl** [comment]
Why is this threat is closed ? the script has crashed my RDP.
which services are required for the RDP ?

**Comment by adolfintel** [comment]
I closed it because it's intended behavior, the guide removes RDP.
The services should be TermService, UmRdpService and SessionEnv if I remember correctly.

**Comment by Julien-nl** [comment]
Maybe is handy to update the tutorial or just add the info that its removes remote desktop ?
i've read the tutorial and cannot seem to find those services on the removed commands or powershell.
that why its got me consufed.
can you confirm which steps on the tutorial are removing the RDP services ?

**Comment by adolfintel** [comment]
They're in the telemetry section, sc delete TermService, etc.

**Comment by Julien-nl** [comment]
good catch thank you.
i just have to exclude those services "TermService, UmRdpService and SessionEnv"and i am set to go ?
if i debot windows using this would it be apply for all other users or have to do it for each user?

**Comment by adolfintel** [comment]
That should be enough but I haven't tested it so let me know if it works.
And yes you have to do it for each user

**Comment by Julien-nl** [comment]
I cannot seem to get them back, is there a way to reinstall them ?

**Comment by adolfintel** [comment]
No, as I said in the intro, you'll have to reinstall windows.
I suggest you try it in a VM first to make sure that it's just those 3 services

**Comment by Julien-nl** [comment]
this unfortunately already happens all i need is to restore RDP. are yo usaying that there is no way of restoring them ?

**Comment by qwertychouskie** [comment]
@Julien-nl Try:
```
DISM /Online /Cleanup-Image /CheckHealth
sfc /scannow
```
Of course this will most likely revert other deletions made, which will then have to be re-applied.

**Comment by qwertychouskie** [comment]
@Julien-nl Try:
```
DISM /Online /Cleanup-Image /RestoreHealth
sfc /scannow
```
Of course this will most likely revert other deletions made, which will then have to be re-applied.

**Comment by Julien-nl** [comment]
unfortunately it didnt works and had to reinstall the windows.
thank you for the scripts.
