### ISSUE TITLE
Windows update broken again

### ISSUE THREAD

**Issue by adolfintel** [adolfintel/Windows10-Privacy#46]
Apparently this time the problem is caused by Edge, it can no longer be fully removed without breaking updates.
I'll see if I can find some other way to deal with it

**Comment by adolfintel** [comment]
Fixed

**Comment by pundoo** [comment]
Just to be confirmed, can you please share the error code you got while updating? I'm getting `0x800F081F`
Not sure if it's related to Edge being removed or something else!

**Comment by adolfintel** [comment]
I think it was that one.
Either way, here's how I find out what's the cause when something like this happens:
* Make a VM with no network and a clean install of Windows
* Run a step of the guide
* Snapshot the VM
* Connect the network and download updates
* If it breaks, find out exactly which command in the step caused the problem using the same technique
* If it doesn't break, restore the last snapshot and continue with the next step
