### ISSUE TITLE
Windows broken

### ISSUE THREAD

**Issue by taich001** [adolfintel/Windows10-Privacy#47]
I want you to know that windows 10 will be broken if you apply your scripts. 

Mainly I think removing the registry keys DPS, WdiServiceHost and WdiSystemHost will lead into that situation that you can not create new users any more. None of the later added users will be able to open startmenu, settings or info center.

The only way to fix this is to reinstall windows again.

If you want to remain owner of your private data just say good bye to windows and use another system.

**Comment by adolfintel** [comment]
It's written in the first paragraph, you won't be able to add new users.

And yes, I have switched to linux as my main OS, even though the user experience is nowhere near as good, windows can't be trusted anymore. I mentioned this in #45 and on my blog.
