### ISSUE TITLE
Minor issue, but...

### ISSUE THREAD

**Issue by ghost** [adolfintel/Windows10-Privacy#50]
Since following the guide, I've noticed that there's a slight difference in how my Start Menu looks. What I mean is this. (
![image](https://user-images.githubusercontent.com/31076197/61582945-50da3f80-ab29-11e9-8bab-7b1e35d8f135.png)

There usually wouldn't be a gap between the edge of the display and the start menu. Any ideas what could've happened? I followed it as close as I can.

**Comment by Barokai** [comment]
this gap was introduced by microsoft with the windows 10 1903 update, they separated the search from the startmenu, now it is placed right of the start button.

edit: check with enabling the search input in the taskbar, then this window opens directly above it when searching something :) 
source: https://www.windowscentral.com/windows-10-may-2019-update-review

> Search is now separate from Cortana, so it no longer has a hamburger menu along the left side. Typically, this wouldn't be a problem, but since Microsoft hasn't updated the UI, it's very obviously missing a hamburger menu now. It just looks stupid having this unnecessary gap that's the exact width of the Start button between the edge of your screen and the beginning of the search UI.

**Comment by adolfintel** [comment]
They added the gap in 1903 so that the search aligns to where the search burron/bar would be.

**Comment by adolfintel** [comment]
Lol, Barokai beat me by a few seconds
