### ISSUE TITLE
Turn off Windows Error reporting

### ISSUE THREAD

**Issue by andregeronimocs** [adolfintel/Windows10-Privacy#6]
Hi, mate. Thanks for your great guides.

One note, though, regarding the Windows Error Reporting:

Your guide specifies the path:
`HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting`

but the correct one is:
`HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting`

Source: https://msdn.microsoft.com/pt-br/library/windows/desktop/bb513638(v=vs.85).aspx

**Comment by adolfintel** [comment]
Strange, I remember seeing that in the group policies.
I'll merge your PR but I'll keep both keys, just for good measure, it won't hurt.

**Comment by adolfintel** [comment]
Sorry, I meant your changes, not PR

**Comment by andregeronimocs** [comment]
Yeah, I think it might be wise to maintain both entries. Found some references of WER on Group Policies here: https://docs.microsoft.com/en-us/enterprise-threat-detection/collector/collector-client-configuration-registry-keys-up-level

**Comment by adolfintel** [comment]
Done
