### ISSUE TITLE
Broken Task View & Data Usage

### ISSUE THREAD

**Issue by NeoTU** [adolfintel/Windows10-Privacy#7]
I've followed everything in the guide and it's greatly appreciated, how ever I've noticed that the "Task View" feature doesn't work and just crashes when pressing the Task View icon on the Taskbar, I like the feature and I'm asking if it's possible to resolve it so it works again? If so what do I need to do exactly to re-enable it if possible please (with or without re-installing).

(Event viewer report:
The shell stopped unexpectedly and explorer.exe was restarted.)

I also noticed that clicking on Data Usage in Network & Internet freezes/crashes the Settings app.
Anyway to resolve this too?

(Event viewer report:
Faulting application name: SystemSettings.exe, version: 10.0.17133.1, time stamp: 0x2a3c4e62
Faulting module name: msvcrt.dll, version: 7.0.17133.1, time stamp: 0x5cbba6fd
Exception code: 0x40000015
Fault offset: 0x000000000000add2
Faulting process id: 0x17c0
Faulting application start time: 0x01d3ca47e26d0908
Faulting application path: C:\Windows\ImmersiveControlPanel\SystemSettings.exe
Faulting module path: C:\Windows\System32\msvcrt.dll
Report Id: b5248ac6-166b-4ca7-b177-8ffa455597af
Faulting package full name: windows.immersivecontrolpanel_10.0.2.1000_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: microsoft.windows.immersivecontrolpanel)

(I'm fresh installed from a bootable USB 3.0 and ran the guide again to verify it is indeed something in the guide breaking these and not drivers/other software installed after the guide).

My ISO: 17133.1.180323-1312.RS4_RELEASE_CLIENTCOMBINED_UUP_X64FRE_EN-US.ISO

**Comment by adolfintel** [comment]
I'm not having the problem with the task view but the data usage doesn't work, which I expected.
Can you narrow down the specific section that's breaking task view for you?

**Comment by adolfintel** [comment]
I found what's breaking task view.
```
sc delete CDPUserSvc
```
I have no idea how it eluded me but I'll see what I can do about it.

**Comment by adolfintel** [comment]
Apparently task view now depends on CDPUserSvc and its friends.

**Comment by NeoTU** [comment]
Just confirmed It's something in "Removing Telemetry and other unnecessary services".
Straight after doing that part and restarting the Task View feature breaks.

Possible to fix without re-installing? (Don't mind if I have to.)

**Comment by adolfintel** [comment]
Nope, I brutally deleted it from the registry so you'll have to reinstall. Sorry.
I'll update the guide with this and another fix in a hour or so.

I'm sorry about this problem, I have no idea why it didn't do that on my system.
