### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by legendarynacar** [adolfintel/Windows10-Privacy#9]
![image](https://user-images.githubusercontent.com/8149261/39534694-1a330d16-4e2a-11e8-8199-0fd843ca0a4d.png)

[icacls Microsoft.Windows.SecHealthUI_cw5n1h2txyewy /grant Everyone:(F) /t /c /q](https://github.com/adolfintel/Windows10-Privacy/blame/master/README.md#L64)

**Comment by adolfintel** [comment]
It's because you're typing it in Powershell. That section says to copy the commands in the command prompt.

**Comment by adolfintel** [comment]
What are you allowing though the firewall?

**Comment by legendarynacar** [comment]
Nothing. I did not add anything , just changed the mode to learning. I will recheck when I get back to my laptop, probably 8-9 hours later.

**Comment by legendarynacar** [comment]
Nothing. I did not add anything , just changed the mode to learning. I will recheck when I get back to my laptop, probably 8-9 hours later.
